model:
  name: "ResNet18"
  num_classes: 4

train:
  lr: 2e-6
  weight_decay: 5e-4
  epochs: 70

data:
  train_path: "ChtoZaLevEtotTigr-4\\train"
  val_path: "ChtoZaLevEtotTigr-4\\valid"
  batch_size: 32